// playgrounds/nextjs/app/src/components/NButton.tsx
"use client";

import { PropsWithChildren } from "react";
import { Button, ButtonStyle } from "@next/chatora"
import { ChatoraWrapper } from "@chatora/react/components/ChatoraWrapper";
import type { Props as ButtonProps, Emits } from "@next/chatora";

type Props = PropsWithChildren<ButtonProps & Partial<Emits>>

export const NButton = ({ children, ...props }: Props) => {
  return (
    <>
      <ChatoraWrapper
        tag="n-button"
        props={props}
        component={Button}
        children={children}
        styles={[ButtonStyle]}
      />
    </>
  )
};

// playgrounds/svelte/src/lib/NButton.svelte
<script lang="ts">
import { Button, type Props, type Emits, ButtonStyle } from "../../chatora"
import { ChatoraWrapper } from "@chatora/svelte";

type $$Props = Props & Emits;
</script>

<ChatoraWrapper
  component={Button}
  tag="n-button"
  props={$$restProps}
  option={{styles: [ButtonStyle]}}
>
  <slot />
</ChatoraWrapper>
