// playgrounds/svelte/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg';
  import viteLogo from '/vite.svg';
  import NButton from './lib/NButton.svelte';

  let count: number = $state(0)
  const increment = () => {
    count += 1
  }
  let type = $state("submit");
/*   setInterval(() => {
    type = type === "submit" ? "button" : "submit";
  }, 1000); */
</script>

<main>
  <div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div class="card">
    <button onclick={increment}>
      count is {count}
    </button>
    {type}
    <NButton type={type} onclick={increment}>
      In Svelte count is {count}
    </NButton>
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

// playgrounds/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import NButton from './components/NButton.vue';

const count = ref(0);

</script>

<template>
  <div>
    <h3>Vite + Vue.js</h3>
  </div>
  <NButton type="submit" @click="() => count++">
    <span>In vue count : {{ count }}</span>
  </NButton>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
