// packages/vue/src/components/ChatoraWrapper.vue
<script setup lang="tsx">
import { type ChatoraComponent, functionalCustomElement, type FunctionalCustomElementOptions, functionalDeclarativeCustomElement } from "chatora";
import { defineProps, h, onMounted, ref, useId, useSlots } from "vue";
import { hastToJsx } from "../utils/hastToJsx";

type Props<P extends Record<string, unknown>> = {
  props: P;
  tag: string;
  component: ChatoraComponent;
} & FunctionalCustomElementOptions;

const {
  tag,
  props: initialProps,
  component,
  ...options
} = defineProps<Props<Record<string, unknown>>>();

const isDefined = ref(false);
const id = useId();
const slots = useSlots();

const tagRef = ref<HTMLElement | null>(null);

const splitProps = (props: Record<string, unknown>) => {
  const emits: Record<string, (event: Event) => void> = {};
  const filteredProps: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (key.startsWith("on-") && typeof value === "function") {
      emits[key] = value as (event: Event) => void;
    }
    else {
      filteredProps[key] = value;
    }
  }
  return { props: filteredProps, emits };
};

const { props, emits } = splitProps(initialProps);

const hast = functionalDeclarativeCustomElement(
  component,
  {
    ...options,
    props: props as Record<string, string | null>,
  },
);

onMounted(() => {
  if (!customElements || customElements.get(tag)) {
    return;
  }

  const Element = functionalCustomElement(
    component,
    options,
  );

  customElements.define(tag, Element);
  isDefined.value = true;

  if (tagRef.value) {
    for (const [key, value] of Object.entries(emits)) {
      if (typeof value === "function") {
        tagRef.value.addEventListener(key, value as EventListener);
      }
    }
  }
});

defineRender(() => {
  // スロット内容を配列として処理
  const slotContent = slots.default ? slots.default() : [];

  return h(tag as any, {
    ref: tagRef,
    ...props,
    // ...emits,
  }, isDefined.value
    ? slotContent
    : hastToJsx(tag, id, hast, slotContent));
});
</script>

// packages/react/src/components/ChatoraWrapper.tsx
import { hastToJsx } from "@/utils/hastToJsx";
import { type ChatoraComponent, functionalCustomElement, type FunctionalCustomElementOptions, functionalDeclarativeCustomElement } from "chatora";
import { type PropsWithChildren, useEffect, useId, useLayoutEffect, useRef, useState } from "react";
import { jsx } from "react/jsx-runtime";

export type Props<P extends Record<string, unknown>> = PropsWithChildren<{
  props: P;
  tag: string;
  component: ChatoraComponent;
} & FunctionalCustomElementOptions>;

const splitProps = (props: Record<string, unknown>) => {
  const emits: Record<string, (event: Event) => void> = {};
  const filteredProps: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (key.startsWith("on-") && typeof value === "function") {
      emits[key] = value as (event: Event) => void;
    }
    else {
      filteredProps[key] = value;
    }
  }
  return { props: filteredProps, emits };
};

export const ChatoraWrapper = <P extends Record<string, unknown>>({ tag, component, children, props, ...option }: Props<P>) => {
  const id = useId();

  const { props: filteredProps, emits } = splitProps(props || {});
  const hast = functionalDeclarativeCustomElement(
    component,
    option,
  );

  const [isDefined, setIsDefined] = useState(false);
  const domRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    const defineElement = () => {
      if (!customElements || customElements.get(tag)) {
        return;
      }

      const element = functionalCustomElement(
        component,
        option,
      );

      customElements.define(tag, element);
      setIsDefined(true);
    };

    defineElement();
  }, [tag, component, option]);

  useLayoutEffect(() => {
    emits && Object.entries(emits).forEach(([event, handler]) => {
      if (typeof handler === "function" && domRef.current) {
        domRef.current.addEventListener(event, handler as EventListener);
      }
    });
    // Cleanup
    return () => {
      emits && Object.entries(emits).forEach(([event, handler]) => {
        if (typeof handler === "function" && domRef.current) {
          domRef.current.removeEventListener(event, handler as EventListener);
        }
      });
    };
  }, [emits]);

  return jsx(tag as any, {
    ...filteredProps,
    ref: domRef,
    children: isDefined ? children : hastToJsx(tag, id, hast, children),
  });
};
