// packages/svelte/src/lib/ChatoraWrapper.svelte
<script lang="ts">
  import type { CC, FunctionalCustomElementOptions } from "chatora";
  import { functionalCustomElement } from "chatora";
  import { onMount } from "svelte";
  // import { browser } from '$app/environment'; // SvelteKitの場合

  export let tag: string;
  export let component: CC;
  export let props: Record<string, string | undefined> = {};
  export let option: FunctionalCustomElementOptions;

  let ref: HTMLElement | null = null;

  let isClient = false;
  let isDefined = false;

  onMount(() => {
    isClient = true;

    const Element = functionalCustomElement(component, { ...option });

    isDefined = customElements.get(tag) !== undefined;

    if (!isDefined) {
      customElements.define(tag, Element);
      isDefined = true;
    }

    if (ref) {
      Object.entries(props).forEach(([key, value]) => {
        if (key.startsWith("on") && value && typeof value === "function") {
          ref!.addEventListener(`on-${key.slice(2).toLowerCase()}`, value);
        }
        else if (value !== undefined) {
          ref!.setAttribute(key, value);
        }
        else {
          ref!.removeAttribute(key);
        }
      });
    }
  });

  $: if (isClient && ref) {
    Object.entries(props).forEach(([key, value]) => {
      if (key.startsWith("on") && value && typeof value === "function") {
        ref!.addEventListener(`on-${key.slice(2).toLowerCase()}`, value);
      }
      else if (value !== undefined) {
        ref!.setAttribute(key, value);
      }
      else {
        ref!.removeAttribute(key);
      }
    });
  }
</script>

{#if isClient}
  <svelte:element bind:this={ref} this={tag}>
    <slot />
  </svelte:element>
{:else}
  <!-- 未実装 -->
  <svelte:element this={tag}>
    <slot />
  </svelte:element>
{/if}

// packages/react/src/components/ChatoraWrapper.tsx
import { hastToJsx } from "@/utils/hastToJsx";
import { type CC, functionalCustomElement, type FunctionalCustomElementOptions, functionalDeclarativeCustomElement } from "chatora";
import { type PropsWithChildren, useEffect, useId, useLayoutEffect, useRef, useState } from "react";
import { jsx } from "react/jsx-runtime";

export type Props<P extends Record<string, unknown>> = PropsWithChildren<{
  props: P;
  tag: string;
  component: CC;
} & FunctionalCustomElementOptions>;

const splitProps = (props: Record<string, unknown>) => {
  const emits: Record<string, (event: Event) => void> = {};
  const filteredProps: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (key.startsWith("on-") && typeof value === "function") {
      emits[key] = value as (event: Event) => void;
    }
    else {
      filteredProps[key] = value;
    }
  }
  return { props: filteredProps, emits };
};

export const ChatoraWrapper = <P extends Record<string, unknown>>({ tag, component, children, props, ...option }: Props<P>) => {
  const id = useId();

  const { props: filteredProps, emits } = splitProps(props || {});

  const hast = functionalDeclarativeCustomElement(
    component,
    {
      ...option,
      props: filteredProps as Record<string, string | undefined>,
    },
  );

  const [isDefined, setIsDefined] = useState(false);
  const domRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    const defineElement = () => {
      if (!customElements || customElements.get(tag)) {
        return;
      }

      const element = functionalCustomElement(
        component,
        option,
      );

      customElements.define(tag, element);
      setIsDefined(true);
    };

    defineElement();
  }, [tag, component, option]);

  useLayoutEffect(() => {
    emits && Object.entries(emits).forEach(([event, handler]) => {
      if (typeof handler === "function" && domRef.current) {
        domRef.current.addEventListener(event, handler as EventListener);
      }
    });
    // Cleanup
    return () => {
      emits && Object.entries(emits).forEach(([event, handler]) => {
        if (typeof handler === "function" && domRef.current) {
          domRef.current.removeEventListener(event, handler as EventListener);
        }
      });
    };
  }, [emits]);

  return jsx(tag as any, {
    ...filteredProps,
    ref: domRef,
    children: isDefined ? children : hastToJsx(tag, id, hast, children),
  });
};
