// playgrounds/svelte/src/lib/NButton.svelte
<script lang="ts">
import { Button, type Props, type Emits, ButtonStyle } from "../../chatora"
import { ChatoraWrapper } from "@chatora/svelte";

type $$Props = Props & Emits;
</script>

<ChatoraWrapper
  component={Button}
  tag="n-button"
  props={$$restProps}
  option={{styles: [ButtonStyle]}}
>
  <slot />
</ChatoraWrapper>

// playgrounds/vue/src/components/NButton.vue
<script setup lang="ts">
import { Button, ButtonStyle, type Props } from "../../chatora/Button"
import ChatoraWrapper from "@chatora/vue/components/ChatoraWrapper.vue"

const props = defineProps<Props>()

type Emits = {
  click: [Event]
  hover: [Event]
  event: [Event]
}

const emits = defineEmits<Emits>()
</script>

<template>
  <ChatoraWrapper
    tag="n-button"
    :component="Button"
    :props="{
      ...props,
      'on-click': (e: Event) => emits('click', e),
      'on-hover': (e: Event) => emits('hover', e),
      'on-event': (e: Event) => emits('event', e),
    }"
    :styles="ButtonStyle"
    :shadow-root="true"
  >
    <slot />
  </ChatoraWrapper>
</template>
